In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("mobile_price.csv")

In [3]:
df.head()

,ram_gb,storage_gb,battery_mah,camera_mp,display_in,processor_score,price
0,4,64,5000,48,6.5,342,43249
1,16,64,6000,108,6.1,230,68977
2,6,128,6000,200,6.1,774,77558
3,16,512,4500,108,6.7,206,93397
4,12,256,5000,48,6.5,981,87062

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ram_gb           500 non-null    int64
 1   storage_gb       500 non-null    int64
 2   battery_mah      500 non-null    int64
 3   camera_mp        500 non-null    int64
 4   display_in       500 non-null    float64
 5   processor_score  500 non-null    int64
 6   price            500 non-null    int64
dtypes: float64(1), int64(6)
memory usage: 27.5 KB

In [5]:
df.isnull().sum()

ram_gb             0
storage_gb         0
battery_mah        0
camera_mp          0
display_in         0
processor_score    0
price              0
dtype: int64

In [6]:
df.describe()

,ram_gb,storage_gb,battery_mah,camera_mp,display_in,processor_score,price
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,9.236000,241.152000,5031.000000,87.360000,6.540600,614.206000,75847.420000
std,4.254469,171.210335,700.371359,63.537204,0.265995,231.433815,15594.668981
min,4.000000,64.000000,4000.000000,12.000000,6.100000,203.000000,40222.000000
25%,6.000000,64.000000,4500.000000,48.000000,6.500000,419.750000,63330.000000
50%,8.000000,256.000000,5000.000000,64.000000,6.700000,622.000000,75463.000000
75%,12.000000,256.000000,5500.000000,108.000000,6.800000,815.250000,86611.750000
max,16.000000,512.000000,6000.000000,200.000000,6.800000,997.000000,118205.000000

In [7]:
x = df.drop("price",axis=1)
y = df["price"]

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [11]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(400, 6)
(100, 6)
(400,)
(100,)